import React, { useState } from "react";
import {
    Container,
    Row,
    Col,
    Card,
    Button,
    Alert,
    Form,
    Badge,
} from "react-bootstrap";

const ShareOptions = ({ groceryItems, onBack }) => {
    const [includePurchased, setIncludePurchased] = useState(false);
    const [shortVersion, setShortVersion] = useState(true);
    const [copied, setCopied] = useState(false);

    const filteredItems = includePurchased
        ? groceryItems
        : groceryItems.filter((item) => !item.purchased);

    const generateShareText = () => {
        if (filteredItems.length === 0) return "My grocery list is empty! 🛒";

        let text = shortVersion
            ? `🛒 Grocery List (${filteredItems.length} items):\n`
            : `🛒 My Grocery Shopping List\nGenerated by DietarySense\n\n`;

        // Simple list without categories for brevity
        filteredItems.slice(0, shortVersion ? 10 : 20).forEach((item) => {
            const status = item.purchased ? "✓ " : "";
            text += `${status}${item.name} (${item.quantity} ${item.unit})\n`;
        });

        if (filteredItems.length > (shortVersion ? 10 : 20)) {
            text += `... and ${filteredItems.length - (shortVersion ? 10 : 20)} more items`;
        }

        text += shortVersion
            ? `\n\nCheck it out on DietarySense!`
            : `\n\nTotal: ${filteredItems.length} items\n\nGenerated on: ${new Date().toLocaleDateString()}`;

        // Truncate for platform limits (WhatsApp ~65k, Twitter 280)
        return text.length > 2000 ? text.substring(0, 2000) + "..." : text;
    };

    const shareText = generateShareText();
    const currentUrl = window.location.origin + "/dashboard/grocery"; // or generate shareable link

    const handleSocialShare = (platform) => {
        let url;
        switch (platform) {
            case "whatsapp":
                url = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
                break;
            case "facebook":
                url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(currentUrl)}&quote=${encodeURIComponent(shareText.substring(0, 200))}`;
                break;
            case "twitter":
                const tweetText = shareText.length > 280 ? shareText.substring(0, 277) + "..." : shareText;
                url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`;
                break;
            case "email":
                url = `mailto:?subject=🛒 My Grocery List&body=${encodeURIComponent(shareText)}`;
                break;
            case "sms":
                url = `sms:?body=${encodeURIComponent(shareText)}`;
                break;
            default:
                return;
        }
        window.open(url, "_blank", "noopener,noreferrer");
    };

    const handleCopyText = async () => {
        try {
            await navigator.clipboard.writeText(shareText);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            // Fallback
            const textArea = document.createElement("textarea");
            textArea.value = shareText;
            document.body.appendChild(textArea);
            textArea.select();
            document.execCommand("copy");
            document.body.removeChild(textArea);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    const handleWebShare = async () => {
        if (navigator.share) {
            try {
                await navigator.share({
                    title: "🛒 My Grocery List",
                    text: shareText.substring(0, 1000),
                    url: currentUrl,
                });
            } catch (err) {
                console.log("Share failed:", err);
            }
        } else {
            handleCopyText();
        }
    };

    const stats = {
        total: filteredItems.length,
        platforms: 6,
    };

    return (
        <Container className="my-4">
            <Row className="justify-content-center">
                <Col lg={10}>
                    <Card className="border-0 shadow">
                        <Card.Header className="bg-info text-white py-3">
                            <div className="d-flex justify-content-between align-items-center">
                                <div>
                                    <h4 className="mb-0">📱 Share Grocery List</h4>
                                    <small className="opacity-75">{stats.total} items ready to share</small>
                                </div>
                                <Button variant="outline-light" size="sm" onClick={onBack}>
                                    ← Back to List
                                </Button>
                            </div>
                        </Card.Header>

                        <Card.Body className="p-4">
                            {/* Share Preview & Options */}
                            <Row className="mb-4">
                                <Col md={6}>
                                    <Card className="border-0 h-100 bg-light">
                                        <Card.Body>
                                            <h6 className="mb-3">✨ Preview</h6>
                                            <Form.Group className="mb-3">
                                                <Form.Check
                                                    type="checkbox"
                                                    id="include-purchased"
                                                    label="Include purchased items"
                                                    checked={includePurchased}
                                                    onChange={(e) => setIncludePurchased(e.target.checked)}
                                                />
                                            </Form.Group>
                                            <Form.Check
                                                type="checkbox"
                                                id="short-version"
                                                label="Short version (for Twitter)"
                                                checked={shortVersion}
                                                onChange={(e) => setShortVersion(e.target.checked)}
                                            />
                                            <div
                                                className="bg-white border rounded p-3 small"
                                                style={{
                                                    maxHeight: "250px",
                                                    overflowY: "auto",
                                                    fontFamily: "monospace",
                                                    whiteSpace: "pre-wrap",
                                                }}
                                            >
                                                {shareText}
                                            </div>
                                        </Card.Body>
                                    </Card>
                                </Col>

                                <Col md={6}>
                                    <Card className="border-0 h-100 bg-light">
                                        <Card.Body>
                                            <h6 className="mb-4">🚀 Share To</h6>

                                            {/* Web Share API (Mobile) */}
                                            <Button
                                                variant="success"
                                                className="w-100 mb-3"
                                                onClick={handleWebShare}
                                                disabled={filteredItems.length === 0}
                                            >
                                                <i className="fas fa-share-alt me-2"></i>
                                                Native Share
                                            </Button>

                                            {/* Social Platforms */}
                                            <div className="row g-2 mb-3">
                                                <div className="col-6">
                                                    <Button
                                                        variant="success"
                                                        size="sm"
                                                        className="w-100"
                                                        onClick={() => handleSocialShare("whatsapp")}
                                                        disabled={filteredItems.length === 0}
                                                    >
                                                        <i className="fab fa-whatsapp me-1"></i>
                                                        WhatsApp
                                                    </Button>
                                                </div>
                                                <div className="col-6">
                                                    <Button
                                                        variant="primary"
                                                        size="sm"
                                                        className="w-100"
                                                        onClick={() => handleSocialShare("facebook")}
                                                        disabled={filteredItems.length === 0}
                                                    >
                                                        <i className="fab fa-facebook-f me-1"></i>
                                                        Facebook
                                                    </Button>
                                                </div>
                                                <div className="col-6">
                                                    <Button
                                                        variant="info"
                                                        size="sm"
                                                        className="w-100"
                                                        onClick={() => handleSocialShare("twitter")}
                                                        disabled={filteredItems.length === 0}
                                                    >
                                                        <i className="fab fa-twitter me-1"></i>
                                                        Twitter
                                                    </Button>
                                                </div>
                                                <div className="col-6">
                                                    <Button
                                                        variant="secondary"
                                                        size="sm"
                                                        className="w-100"
                                                        onClick={handleCopyText}
                                                        disabled={filteredItems.length === 0}
                                                    >
                                                        <i className="fas fa-copy me-1"></i>
                                                        {copied ? "Copied!" : "Copy Text"}
                                                    </Button>
                                                </div>
                                                <div className="col-6">
                                                    <Button
                                                        variant="outline-danger"
                                                        size="sm"
                                                        className="w-100"
                                                        onClick={() => handleSocialShare("email")}
                                                        disabled={filteredItems.length === 0}
                                                    >
                                                        <i className="fas fa-envelope me-1"></i>
                                                        Email
                                                    </Button>
                                                </div>
                                                <div className="col-6">
                                                    <Button
                                                        variant="outline-primary"
                                                        size="sm"
                                                        className="w-100"
                                                        onClick={() => handleSocialShare("sms")}
                                                        disabled={filteredItems.length === 0}
                                                    >
                                                        <i className="fas fa-sms me-1"></i>
                                                        SMS
                                                    </Button>
                                                </div>
                                            </div>

                                            <Alert variant="info" className="small mb-0">
                                                <i className="fas fa-info-circle me-1"></i>
                                                <strong>Instagram:</strong> Copy text above and paste in DM/Story. No direct API link.
                                            </Alert>
                                        </Card.Body>
                                    </Card>
                                </Col>
                            </Row>

                            {filteredItems.length === 0 && (
                                <Alert variant="warning" className="text-center">
                                    <i className="fas fa-shopping-cart me-2"></i>
                                    Add items to your grocery list first!
                                </Alert>
                            )}
                        </Card.Body>
                    </Card>
                </Col>
            </Row>
        </Container>
    );
};

export default ShareOptions;

